export enum AuditAction {
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS',
  DELETE_TASK = 'DELETE_TASK',
  UPDATE_ROLE = 'UPDATE_ROLE',
  USER_LOGIN = 'USER_LOGIN',
}
